-- DDL --

DROP TABLE IF EXISTS bank CASCADE;
DROP TABLE IF EXISTS client CASCADE;
DROP TABLE IF EXISTS credit CASCADE;
DROP TABLE IF EXISTS creditoffer CASCADE;
DROP TABLE IF EXISTS paymentSchedule CASCADE;
DROP TABLE IF EXISTS ps_user CASCADE;
DROP TABLE IF EXISTS ps_role CASCADE;
--
--DELETE FROM DATABASECHANGELOGLOCK where ID = 1;
--
